name: Claude Code

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude-code:
    if: |
      contains(github.event.comment.body || github.event.review.body || github.event.issue.body || github.event.pull_request.body || '', '@claude') ||
      contains(github.event.issue.title || github.event.pull_request.title || '', '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v0.0.33
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}